In [24]:
import os

In [25]:
import numpy

In [26]:
distance_file = os.path.join('buckminsterfullerene.xyz')
n = 60

In [27]:
distances = numpy.genfromtxt(distance_file, dtype='unicode', skip_header=2)
headers = distances[:,0]
print(headers)
#print(distances)

['C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C']


In [28]:
data = distances[:,1:]
print(data)

[['0.0000' '1.2363' '3.3275']
 ['-1.1758' '0.3820' '3.3275']
 ['-0.7267' '-1.0002' '3.3275']
 ['0.7267' '-1.0002' '3.3275']
 ['1.1758' '0.3820' '3.3275']
 ['2.3047' '0.7489' '2.5939']
 ['3.0314' '-0.2513' '1.8298']
 ['2.6002' '-1.5785' '1.8298']
 ['1.4244' '-1.9605' '2.5939']
 ['0.6977' '-2.9607' '1.8298']
 ['-0.6977' '-2.9607' '1.8298']
 ['-1.4244' '-1.9605' '2.5939']
 ['-2.6002' '-1.5785' '1.8298']
 ['-3.0314' '-0.2513' '1.8298']
 ['-2.3047' '0.7489' '2.5939']
 ['-2.3047' '1.9852' '1.8298']
 ['-3.0314' '1.7490' '0.5935']
 ['-3.4805' '0.3668' '0.5935']
 ['-3.4805' '-0.3668' '-0.5935']
 ['-3.0314' '-1.7490' '-0.5935']
 ['-2.6002' '-2.3426' '0.5935']
 ['-1.4244' '-3.1968' '0.5935']
 ['-0.7267' '-3.4235' '-0.5935']
 ['0.7267' '-3.4235' '-0.5935']
 ['1.4244' '-3.1968' '0.5935']
 ['2.6002' '-2.3426' '0.5935']
 ['3.0314' '-1.7490' '-0.5935']
 ['3.4805' '-0.3668' '-0.5935']
 ['3.4805' '0.3668' '0.5935']
 ['3.0314' '1.7490' '0.5935']
 ['2.6002' '2.3426' '-0.5935']
 ['2.6002' '1.5785' '-1.8298

In [29]:
A = data.astype(numpy.float)
print(A)

[[ 0.      1.2363  3.3275]
 [-1.1758  0.382   3.3275]
 [-0.7267 -1.0002  3.3275]
 [ 0.7267 -1.0002  3.3275]
 [ 1.1758  0.382   3.3275]
 [ 2.3047  0.7489  2.5939]
 [ 3.0314 -0.2513  1.8298]
 [ 2.6002 -1.5785  1.8298]
 [ 1.4244 -1.9605  2.5939]
 [ 0.6977 -2.9607  1.8298]
 [-0.6977 -2.9607  1.8298]
 [-1.4244 -1.9605  2.5939]
 [-2.6002 -1.5785  1.8298]
 [-3.0314 -0.2513  1.8298]
 [-2.3047  0.7489  2.5939]
 [-2.3047  1.9852  1.8298]
 [-3.0314  1.749   0.5935]
 [-3.4805  0.3668  0.5935]
 [-3.4805 -0.3668 -0.5935]
 [-3.0314 -1.749  -0.5935]
 [-2.6002 -2.3426  0.5935]
 [-1.4244 -3.1968  0.5935]
 [-0.7267 -3.4235 -0.5935]
 [ 0.7267 -3.4235 -0.5935]
 [ 1.4244 -3.1968  0.5935]
 [ 2.6002 -2.3426  0.5935]
 [ 3.0314 -1.749  -0.5935]
 [ 3.4805 -0.3668 -0.5935]
 [ 3.4805  0.3668  0.5935]
 [ 3.0314  1.749   0.5935]
 [ 2.6002  2.3426 -0.5935]
 [ 2.6002  1.5785 -1.8298]
 [ 3.0314  0.2513 -1.8298]
 [ 2.3047 -0.7489 -2.5939]
 [ 2.3047 -1.9852 -1.8298]
 [ 1.1758 -2.8054 -1.8298]
 [ 0.     -2.4234 -2.5939]
 

In [30]:
A = distances[:,1:]
print(A)

[['0.0000' '1.2363' '3.3275']
 ['-1.1758' '0.3820' '3.3275']
 ['-0.7267' '-1.0002' '3.3275']
 ['0.7267' '-1.0002' '3.3275']
 ['1.1758' '0.3820' '3.3275']
 ['2.3047' '0.7489' '2.5939']
 ['3.0314' '-0.2513' '1.8298']
 ['2.6002' '-1.5785' '1.8298']
 ['1.4244' '-1.9605' '2.5939']
 ['0.6977' '-2.9607' '1.8298']
 ['-0.6977' '-2.9607' '1.8298']
 ['-1.4244' '-1.9605' '2.5939']
 ['-2.6002' '-1.5785' '1.8298']
 ['-3.0314' '-0.2513' '1.8298']
 ['-2.3047' '0.7489' '2.5939']
 ['-2.3047' '1.9852' '1.8298']
 ['-3.0314' '1.7490' '0.5935']
 ['-3.4805' '0.3668' '0.5935']
 ['-3.4805' '-0.3668' '-0.5935']
 ['-3.0314' '-1.7490' '-0.5935']
 ['-2.6002' '-2.3426' '0.5935']
 ['-1.4244' '-3.1968' '0.5935']
 ['-0.7267' '-3.4235' '-0.5935']
 ['0.7267' '-3.4235' '-0.5935']
 ['1.4244' '-3.1968' '0.5935']
 ['2.6002' '-2.3426' '0.5935']
 ['3.0314' '-1.7490' '-0.5935']
 ['3.4805' '-0.3668' '-0.5935']
 ['3.4805' '0.3668' '0.5935']
 ['3.0314' '1.7490' '0.5935']
 ['2.6002' '2.3426' '-0.5935']
 ['2.6002' '1.5785' '-1.8298

In [31]:
A = A.astype(numpy.float)
print(A)

[[ 0.      1.2363  3.3275]
 [-1.1758  0.382   3.3275]
 [-0.7267 -1.0002  3.3275]
 [ 0.7267 -1.0002  3.3275]
 [ 1.1758  0.382   3.3275]
 [ 2.3047  0.7489  2.5939]
 [ 3.0314 -0.2513  1.8298]
 [ 2.6002 -1.5785  1.8298]
 [ 1.4244 -1.9605  2.5939]
 [ 0.6977 -2.9607  1.8298]
 [-0.6977 -2.9607  1.8298]
 [-1.4244 -1.9605  2.5939]
 [-2.6002 -1.5785  1.8298]
 [-3.0314 -0.2513  1.8298]
 [-2.3047  0.7489  2.5939]
 [-2.3047  1.9852  1.8298]
 [-3.0314  1.749   0.5935]
 [-3.4805  0.3668  0.5935]
 [-3.4805 -0.3668 -0.5935]
 [-3.0314 -1.749  -0.5935]
 [-2.6002 -2.3426  0.5935]
 [-1.4244 -3.1968  0.5935]
 [-0.7267 -3.4235 -0.5935]
 [ 0.7267 -3.4235 -0.5935]
 [ 1.4244 -3.1968  0.5935]
 [ 2.6002 -2.3426  0.5935]
 [ 3.0314 -1.749  -0.5935]
 [ 3.4805 -0.3668 -0.5935]
 [ 3.4805  0.3668  0.5935]
 [ 3.0314  1.749   0.5935]
 [ 2.6002  2.3426 -0.5935]
 [ 2.6002  1.5785 -1.8298]
 [ 3.0314  0.2513 -1.8298]
 [ 2.3047 -0.7489 -2.5939]
 [ 2.3047 -1.9852 -1.8298]
 [ 1.1758 -2.8054 -1.8298]
 [ 0.     -2.4234 -2.5939]
 

In [32]:
A_1 = numpy.zeros((n,n))
for num1 in range(n):
    for num2 in range(n):
        A_1[num1,num2] = (numpy.sqrt((A[num1,0]-A[num2,0])**2+(A[num1,1]-A[num2,1])**2+(A[num1,2]-A[num2,2])**2))
print(A_1)

[[0.         1.45338712 2.35160055 ... 1.39548392 2.4673236  2.84878897]
 [1.45338712 0.         1.45332985 ... 2.46738496 3.69404865 4.11427221]
 [2.35160055 1.45332985 0.         ... 3.57593328 4.5105657  4.51055478]
 ...
 [1.39548392 2.46738496 3.57593328 ... 0.         1.45336797 2.46728801]
 [2.4673236  3.69404865 4.5105657  ... 1.45336797 0.         1.39540075]
 [2.84878897 4.11427221 4.51055478 ... 2.46728801 1.39540075 0.        ]]


In [33]:
for i in range(n):
    for j in range(n):
        print('{0:2s} to {1}: {2:.5f}'.format(headers[i], headers[j], A_1[i,j]))

C  to C: 0.00000
C  to C: 1.45339
C  to C: 2.35160
C  to C: 2.35160
C  to C: 1.45339
C  to C: 2.46726
C  to C: 3.69397
C  to C: 4.11427
C  to C: 3.57584
C  to C: 4.51051
C  to C: 4.51051
C  to C: 3.57584
C  to C: 4.11427
C  to C: 3.69397
C  to C: 2.46726
C  to C: 2.84879
C  to C: 4.11424
C  to C: 4.51051
C  to C: 5.48252
C  to C: 5.78581
C  to C: 5.20042
C  to C: 5.39963
C  to C: 6.13319
C  to C: 6.13319
C  to C: 5.39963
C  to C: 5.20042
C  to C: 5.78581
C  to C: 5.48252
C  to C: 4.51051
C  to C: 4.11424
C  to C: 4.83313
C  to C: 5.78583
C  to C: 6.06278
C  to C: 6.65700
C  to C: 6.50288
C  to C: 6.65700
C  to C: 6.96106
C  to C: 6.65700
C  to C: 6.50288
C  to C: 6.65700
C  to C: 6.06278
C  to C: 5.78583
C  to C: 4.83313
C  to C: 4.60942
C  to C: 5.48253
C  to C: 6.13322
C  to C: 6.69872
C  to C: 6.94913
C  to C: 7.09949
C  to C: 6.94913
C  to C: 6.69872
C  to C: 6.13322
C  to C: 5.48253
C  to C: 4.60942
C  to C: 3.57585
C  to C: 3.57585
C  to C: 2.46732
C  to C: 1.39548
C  to C: 2.467

C  to C: 2.46728
C  to C: 3.57584
C  to C: 4.60950
C  to C: 5.48263
C  to C: 6.13324
C  to C: 5.78589
C  to C: 4.83316
C  to C: 4.11429
C  to C: 2.84885
C  to C: 2.46732
C  to C: 3.69405
C  to C: 4.51057
C  to C: 5.48258
C  to C: 6.06283
C  to C: 6.65702
C  to C: 6.94918
C  to C: 6.69875
C  to C: 6.69879
C  to C: 6.94924
C  to C: 7.09956
C  to C: 6.96106
C  to C: 6.50288
C  to C: 5.78583
C  to C: 5.48252
C  to C: 6.06278
C  to C: 6.65697
C  to C: 6.94917
C  to C: 6.69873
C  to C: 6.13320
C  to C: 5.78584
C  to C: 4.83308
C  to C: 4.11421
C  to C: 4.51051
C  to C: 3.69397
C  to C: 4.11426
C  to C: 5.20043
C  to C: 5.39970
C  to C: 4.51051
C  to C: 3.57586
C  to C: 2.35163
C  to C: 1.45338
C  to C: 2.46727
C  to C: 2.84873
C  to C: 2.46723
C  to C: 3.57583
C  to C: 4.60940
C  to C: 5.48253
C  to C: 5.48254
C  to C: 6.13320
C  to C: 6.69872
C  to C: 6.94914
C  to C: 6.65705
C  to C: 6.06284
C  to C: 5.78584
C  to C: 4.83310
C  to C: 4.60940
C  to C: 3.57584
C  to C: 2.46729
C  to C: 1.395

In [ ]:
len()