In [2]:
import os

In [3]:
import numpy

In [4]:
distance_file = os.path.join('water.xyz')

In [158]:
distances = numpy.genfromtxt(distance_file, dtype='unicode', skip_header=2)
headers = distances[:,0]
print(headers)
#print(distances)

['O' 'H1' 'H2']


In [145]:
data = distances[:,1:]
print(data)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [146]:
A = data.astype(numpy.float)
print(A)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [147]:
A = distances[:,1:]
print(A)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [150]:
A = A.astype(numpy.float)
print(A)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [157]:
A_1 = numpy.zeros((3,3))
for num1 in range(3):
    for num2 in range(3):
        A_1[num1,num2] = (numpy.sqrt((A[num1,0]-A[num2,0])**2+(A[num1,1]-A[num2,1])**2+(A[num1,2]-A[num2,2])**2))
print(A_1)

[[0.         0.96900054 0.96900033]
 [0.96900054 0.         1.52693634]
 [0.96900033 1.52693634 0.        ]]


In [168]:
for i in range(3):
    for j in range(3):
        print('{0:2s} to {1}: {2:.5f}'.format(headers[i], headers[j], A_1[i,j]))

O  to O: 0.00000
O  to H1: 0.96900
O  to H2: 0.96900
H1 to O: 0.96900
H1 to H1: 0.00000
H1 to H2: 1.52694
H2 to O: 0.96900
H2 to H1: 1.52694
H2 to H2: 0.00000
